FROM golang:1.24 AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /out/ember-operator ./operator/cmd/operator

FROM scratch
COPY --from=build /out/ember-operator /ember-operator
USER 65532:65532
ENTRYPOINT ["/ember-operator"]
