apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - ../../operator/config/crd
  - ../../operator/config/rbac
  - ../../operator/config/policy
  - ../../operator/config/manager
  - ../../gateway/config
  - ../../controlapi/config
  - ../../monitoring/config
  - postgres-storage.yaml
  - fake-gpu-daemonset.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: ember-control-api
      namespace: ember-system
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --secure-cookies=false
  - target:
      group: apps
      version: v1
      kind: StatefulSet
      name: ember-postgres
      namespace: ember-system
    path: postgres-statefulset-patch.yaml
