apiVersion: v1
kind: ServiceAccount
metadata:
  name: ember-prometheus
  namespace: ember-system
  labels:
    app.kubernetes.io/name: ember-prometheus
    app.kubernetes.io/part-of: ember
    component: prometheus
automountServiceAccountToken: false
