apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: ember-gateway
  namespace: ember-system
  labels:
    app.kubernetes.io/name: ember-public-gateway
    app.kubernetes.io/part-of: ember
spec:
  default:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 2
    unhealthyThreshold: 2
    config:
      type: HTTP
      httpHealthCheck:
        portSpecification: USE_FIXED_PORT
        port: 8080
        requestPath: /healthz
  targetRef:
    group: ""
    kind: Service
    name: ember-gateway
